#include <stdio.h>
#define alert printf
#define prompt scanf
#include <locale.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <windows.h>

int loadingscreen ( )
    {
    setlocale (LC_ALL,"");
    setlocale (LC_CTYPE,"pt_BR.UTF-8" );
    char porcento = '%';
    alert("\n\n\n\n\n\t\t\t  github.com/pedrohjsilva\n\n\n\n");
    Sleep(4000);
    system("cls"); // ao limparmos a tela, conseguimos dar sequência nas transições, em vez de apenas imprimirmos mais conteúdo na tela
    alert("\n\n\n\n\n\t\t\t  CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS\n\n\n");
    alert("\t\t\t\t    Graduação em Engenharia Mecânica\n\n\n");
    alert("\t\t\t\tLaboratório de programação em computadores I\n\n\n\n\n");
    Sleep(4000);
    system("cls");
    alert("\n\n\n\n\n\n\n\t\t\t\t\   © 2022. SILVA, Pedro Henrique\n\n\n\n\n");
    alert("\t\t\t\t\tAll rights reserved\n\n\n\n\n\n");
    Sleep(4000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  0%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  1%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  2%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  3%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  4%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  5%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  6%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  7%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  8%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[----------]  9%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  10%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  11%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  12%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  13%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  14%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  15%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  16%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  17%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  18%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=---------]  19%c\n\n\n", porcento);
    Sleep(800);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  20%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  21%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  22%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  23%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  24%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  25%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  26%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  27%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  28%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==--------]  29%c\n\n\n", porcento);
    Sleep(850);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  30%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  31%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  32%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  33%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  34%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  35%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  36%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  37%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  38%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[===-------]  39%c\n\n\n", porcento);
    Sleep(600);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  40%c\n\n\n", porcento);
    Sleep(300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  41%c\n\n\n", porcento);
    Sleep(300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  42%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  43%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  44%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  45%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  46%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  47%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  48%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[====------]  49%c\n\n\n", porcento);
    Sleep(1300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  50%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  51%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  52%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  53%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  54%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  55%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  56%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  57%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  58%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=====-----]  59%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  60%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  61%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  62%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  63%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  64%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  65%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  66%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  67%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  68%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[======----]  69%c\n\n\n", porcento);
    Sleep(200);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  70%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  71%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  72%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  73%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  74%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  75%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  76%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  77%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  78%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=======---]  79%c\n\n\n", porcento);
    Sleep(720);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  80%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  81%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  82%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  83%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  84%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  85%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  86%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  87%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  88%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[========--]  89%c\n\n\n", porcento);
    Sleep(2000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  90%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  91%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  92%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  93%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  94%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  95%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  96%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  97%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  98%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[=========-]  99%c\n\n\n", porcento);
    Sleep(2300);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==========]  99%c\n\n\n", porcento);
    Sleep(4000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t\t  CARREGANDO...");
    alert("\n\n\t\t\t\t\t\t[==========]  100%c\n\n\n", porcento);
    Sleep(1000);
    system("cls");
    alert("\n\n\n\n\n\n\n\n\t\t\t\t\t  CARREGAMENTO CONCLUÍDO...");
    alert("\n\n\t\t\t\tPressione qualquer tecla para continuar\n\n\n");
    prompt("");
    system("cls");
    }
